/*
 * This file is generated by jOOQ.
 */
package com.ispy.ispy.jooq.com.ispy.spy.jooq.tables


import com.ispy.ispy.jooq.com.ispy.spy.jooq.Public
import com.ispy.ispy.jooq.com.ispy.spy.jooq.keys.METADATA_PKEY
import com.ispy.ispy.jooq.com.ispy.spy.jooq.keys.METADATA__METADATA_IMAGE_ID_FKEY
import com.ispy.ispy.jooq.com.ispy.spy.jooq.tables.Images.ImagesPath
import com.ispy.ispy.jooq.com.ispy.spy.jooq.tables.records.MetadataRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Metadata(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MetadataRecord>?,
    parentPath: InverseForeignKey<out Record, MetadataRecord>?,
    aliased: Table<MetadataRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MetadataRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.metadata</code>
         */
        val METADATA: Metadata = Metadata()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MetadataRecord> = MetadataRecord::class.java

    /**
     * The column <code>public.metadata.metadata_id</code>.
     */
    val METADATA_ID: TableField<MetadataRecord, Int?> = createField(DSL.name("metadata_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.metadata.image_id</code>.
     */
    val IMAGE_ID: TableField<MetadataRecord, Int?> = createField(DSL.name("image_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.metadata.metadata</code>.
     */
    val METADATA_: TableField<MetadataRecord, JSONB?> = createField(DSL.name("metadata"), SQLDataType.JSONB, this, "")

    private constructor(alias: Name, aliased: Table<MetadataRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MetadataRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MetadataRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.metadata</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.metadata</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.metadata</code> table reference
     */
    constructor(): this(DSL.name("metadata"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MetadataRecord>?, parentPath: InverseForeignKey<out Record, MetadataRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, METADATA, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MetadataPath : Metadata, Path<MetadataRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MetadataRecord>?, parentPath: InverseForeignKey<out Record, MetadataRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MetadataRecord>): super(alias, aliased)
        override fun `as`(alias: String): MetadataPath = MetadataPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MetadataPath = MetadataPath(alias, this)
        override fun `as`(alias: Table<*>): MetadataPath = MetadataPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<MetadataRecord, Int?> = super.getIdentity() as Identity<MetadataRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<MetadataRecord> = METADATA_PKEY
    override fun getReferences(): List<ForeignKey<MetadataRecord, *>> = listOf(METADATA__METADATA_IMAGE_ID_FKEY)

    private lateinit var _images: ImagesPath

    /**
     * Get the implicit join path to the <code>public.images</code> table.
     */
    fun images(): ImagesPath {
        if (!this::_images.isInitialized)
            _images = ImagesPath(this, METADATA__METADATA_IMAGE_ID_FKEY, null)

        return _images;
    }

    val images: ImagesPath
        get(): ImagesPath = images()
    override fun `as`(alias: String): Metadata = Metadata(DSL.name(alias), this)
    override fun `as`(alias: Name): Metadata = Metadata(alias, this)
    override fun `as`(alias: Table<*>): Metadata = Metadata(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Metadata = Metadata(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Metadata = Metadata(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Metadata = Metadata(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Metadata = Metadata(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Metadata = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Metadata = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Metadata = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Metadata = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Metadata = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Metadata = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Metadata = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Metadata = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Metadata = where(DSL.notExists(select))
}
