services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    container_name: backend-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
