spring.application.name=ispy
spring.datasource.url=jdbc:postgresql://localhost:5432/ispy_db
spring.datasource.username=anastasialukavsky
spring.datasource.password=postgrespass
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.jooq=debug

spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
graphql.servlet.mapping=/graphql
graphql.servlet.enabled=true
graphql.servlet.cors.enabled=true