/*
 * This file is generated by jOOQ.
 */
package com.ispy.spy.jooq


import com.ispy.spy.jooq.tables.ElaResults
import com.ispy.spy.jooq.tables.Images
import com.ispy.spy.jooq.tables.NoiseAnalysisResults
import com.ispy.spy.jooq.tables.Users

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.ela_results</code>.
     */
    val ELA_RESULTS: ElaResults get() = ElaResults.ELA_RESULTS

    /**
     * The table <code>public.images</code>.
     */
    val IMAGES: Images get() = Images.IMAGES

    /**
     * The table <code>public.noise_analysis_results</code>.
     */
    val NOISE_ANALYSIS_RESULTS: NoiseAnalysisResults get() = NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS

    /**
     * The table <code>public.users</code>.
     */
    val USERS: Users get() = Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        ElaResults.ELA_RESULTS,
        Images.IMAGES,
        NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS,
        Users.USERS
    )
}
