/*
 * This file is generated by jOOQ.
 */
package com.ispy.ispy.jooq.tables


import com.ispy.ispy.jooq.Public
import com.ispy.ispy.jooq.keys.GEOLOCATION_IMAGE_ID_KEY
import com.ispy.ispy.jooq.keys.GEOLOCATION_PKEY
import com.ispy.ispy.jooq.keys.GEOLOCATION__GEOLOCATION_IMAGE_ID_FKEY
import com.ispy.ispy.jooq.tables.Images.ImagesPath
import com.ispy.ispy.jooq.tables.records.GeolocationRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Geolocation(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GeolocationRecord>?,
    parentPath: InverseForeignKey<out Record, GeolocationRecord>?,
    aliased: Table<GeolocationRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GeolocationRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.geolocation</code>
         */
        val GEOLOCATION: Geolocation = Geolocation()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GeolocationRecord> = GeolocationRecord::class.java

    /**
     * The column <code>public.geolocation.id</code>.
     */
    val ID: TableField<GeolocationRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.geolocation.image_id</code>.
     */
    val IMAGE_ID: TableField<GeolocationRecord, Int?> = createField(DSL.name("image_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.geolocation.latitude</code>.
     */
    val LATITUDE: TableField<GeolocationRecord, Double?> = createField(DSL.name("latitude"), SQLDataType.DOUBLE.nullable(false), this, "")

    /**
     * The column <code>public.geolocation.longitude</code>.
     */
    val LONGITUDE: TableField<GeolocationRecord, Double?> = createField(DSL.name("longitude"), SQLDataType.DOUBLE.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<GeolocationRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GeolocationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GeolocationRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.geolocation</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.geolocation</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.geolocation</code> table reference
     */
    constructor(): this(DSL.name("geolocation"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GeolocationRecord>?, parentPath: InverseForeignKey<out Record, GeolocationRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GEOLOCATION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GeolocationPath : Geolocation, Path<GeolocationRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GeolocationRecord>?, parentPath: InverseForeignKey<out Record, GeolocationRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GeolocationRecord>): super(alias, aliased)
        override fun `as`(alias: String): GeolocationPath = GeolocationPath(DSL.name(alias), this)
        override fun `as`(alias: Name): GeolocationPath = GeolocationPath(alias, this)
        override fun `as`(alias: Table<*>): GeolocationPath = GeolocationPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<GeolocationRecord, Int?> = super.getIdentity() as Identity<GeolocationRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<GeolocationRecord> = GEOLOCATION_PKEY
    override fun getUniqueKeys(): List<UniqueKey<GeolocationRecord>> = listOf(GEOLOCATION_IMAGE_ID_KEY)
    override fun getReferences(): List<ForeignKey<GeolocationRecord, *>> = listOf(GEOLOCATION__GEOLOCATION_IMAGE_ID_FKEY)

    private lateinit var _images: ImagesPath

    /**
     * Get the implicit join path to the <code>public.images</code> table.
     */
    fun images(): ImagesPath {
        if (!this::_images.isInitialized)
            _images = ImagesPath(this, GEOLOCATION__GEOLOCATION_IMAGE_ID_FKEY, null)

        return _images;
    }

    val images: ImagesPath
        get(): ImagesPath = images()
    override fun `as`(alias: String): Geolocation = Geolocation(DSL.name(alias), this)
    override fun `as`(alias: Name): Geolocation = Geolocation(alias, this)
    override fun `as`(alias: Table<*>): Geolocation = Geolocation(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Geolocation = Geolocation(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Geolocation = Geolocation(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Geolocation = Geolocation(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Geolocation = Geolocation(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Geolocation = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Geolocation = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Geolocation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Geolocation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Geolocation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Geolocation = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Geolocation = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Geolocation = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Geolocation = where(DSL.notExists(select))
}
