/*
 * This file is generated by jOOQ.
 */
package com.ispy.spy.jooq.tables.records


import com.ispy.spy.jooq.tables.Geolocation

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GeolocationRecord() : UpdatableRecordImpl<GeolocationRecord>(Geolocation.GEOLOCATION) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var imageId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var latitude: Double?
        set(value): Unit = set(2, value)
        get(): Double? = get(2) as Double?

    open var longitude: Double?
        set(value): Unit = set(3, value)
        get(): Double? = get(3) as Double?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised GeolocationRecord
     */
    constructor(id: Int? = null, imageId: Int? = null, latitude: Double? = null, longitude: Double? = null): this() {
        this.id = id
        this.imageId = imageId
        this.latitude = latitude
        this.longitude = longitude
        resetChangedOnNotNull()
    }
}
