/*
 * This file is generated by jOOQ.
 */
package com.ispy.spy.jooq.tables.records


import com.ispy.spy.jooq.tables.HistoricalWeather

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class HistoricalWeatherRecord() : UpdatableRecordImpl<HistoricalWeatherRecord>(HistoricalWeather.HISTORICAL_WEATHER) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var imageId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var historicalWeather: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised HistoricalWeatherRecord
     */
    constructor(id: Int? = null, imageId: Int? = null, historicalWeather: String? = null): this() {
        this.id = id
        this.imageId = imageId
        this.historicalWeather = historicalWeather
        resetChangedOnNotNull()
    }
}
