/*
 * This file is generated by jOOQ.
 */
package com.ispy.spy.jooq.tables.records


import com.ispy.spy.jooq.tables.Metadata

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MetadataRecord() : UpdatableRecordImpl<MetadataRecord>(Metadata.METADATA) {

    open var metadataId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var imageId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var metadata: JSONB?
        set(value): Unit = set(2, value)
        get(): JSONB? = get(2) as JSONB?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised MetadataRecord
     */
    constructor(metadataId: Int? = null, imageId: Int? = null, metadata: JSONB? = null): this() {
        this.metadataId = metadataId
        this.imageId = imageId
        this.metadata = metadata
        resetChangedOnNotNull()
    }
}
