/*
 * This file is generated by jOOQ.
 */
package com.ispy.spy.jooq.tables.references


import com.ispy.spy.jooq.tables.ElaResults
import com.ispy.spy.jooq.tables.Images
import com.ispy.spy.jooq.tables.NoiseAnalysisResults
import com.ispy.spy.jooq.tables.Users



/**
 * The table <code>public.ela_results</code>.
 */
val ELA_RESULTS: ElaResults = ElaResults.ELA_RESULTS

/**
 * The table <code>public.images</code>.
 */
val IMAGES: Images = Images.IMAGES

/**
 * The table <code>public.noise_analysis_results</code>.
 */
val NOISE_ANALYSIS_RESULTS: NoiseAnalysisResults = NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
