/*
 * This file is generated by jOOQ.
 */
package com.ispy.ispy.jooq.tables.references


import com.ispy.ispy.jooq.tables.DeepLearningWeatherAnalizer
import com.ispy.ispy.jooq.tables.ElaResults
import com.ispy.ispy.jooq.tables.Geolocation
import com.ispy.ispy.jooq.tables.HistoricalWeather
import com.ispy.ispy.jooq.tables.Images
import com.ispy.ispy.jooq.tables.Metadata
import com.ispy.ispy.jooq.tables.NoiseAnalysisResults
import com.ispy.ispy.jooq.tables.Users



/**
 * The table <code>public.deep_learning_weather_analizer</code>.
 */
val DEEP_LEARNING_WEATHER_ANALIZER: DeepLearningWeatherAnalizer = DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER

/**
 * The table <code>public.ela_results</code>.
 */
val ELA_RESULTS: ElaResults = ElaResults.ELA_RESULTS

/**
 * The table <code>public.geolocation</code>.
 */
val GEOLOCATION: Geolocation = Geolocation.GEOLOCATION

/**
 * The table <code>public.historical_weather</code>.
 */
val HISTORICAL_WEATHER: HistoricalWeather = HistoricalWeather.HISTORICAL_WEATHER

/**
 * The table <code>public.images</code>.
 */
val IMAGES: Images = Images.IMAGES

/**
 * The table <code>public.metadata</code>.
 */
val METADATA: Metadata = Metadata.METADATA

/**
 * The table <code>public.noise_analysis_results</code>.
 */
val NOISE_ANALYSIS_RESULTS: NoiseAnalysisResults = NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
