/*
 * This file is generated by jOOQ.
 */
package com.ispy.ispy.jooq.com.ispy.spy.jooq.keys


import com.ispy.spy.jooq.tables.DeepLearningWeatherAnalizer
import com.ispy.spy.jooq.tables.ElaResults
import com.ispy.spy.jooq.tables.Geolocation
import com.ispy.spy.jooq.tables.HistoricalWeather
import com.ispy.spy.jooq.tables.Images
import com.ispy.spy.jooq.tables.Metadata
import com.ispy.spy.jooq.tables.NoiseAnalysisResults
import com.ispy.spy.jooq.tables.Users
import com.ispy.spy.jooq.tables.records.DeepLearningWeatherAnalizerRecord
import com.ispy.spy.jooq.tables.records.ElaResultsRecord
import com.ispy.spy.jooq.tables.records.GeolocationRecord
import com.ispy.spy.jooq.tables.records.HistoricalWeatherRecord
import com.ispy.spy.jooq.tables.records.ImagesRecord
import com.ispy.spy.jooq.tables.records.MetadataRecord
import com.ispy.spy.jooq.tables.records.NoiseAnalysisResultsRecord
import com.ispy.spy.jooq.tables.records.UsersRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val DEEP_LEARNING_WEATHER_ANALIZER_IMAGE_ID_KEY: UniqueKey<DeepLearningWeatherAnalizerRecord> = Internal.createUniqueKey(DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER, DSL.name("deep_learning_weather_analizer_image_id_key"), arrayOf(DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER.IMAGE_ID), true)
val DEEP_LEARNING_WEATHER_ANALIZER_PKEY: UniqueKey<DeepLearningWeatherAnalizerRecord> = Internal.createUniqueKey(DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER, DSL.name("deep_learning_weather_analizer_pkey"), arrayOf(DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER.ID), true)
val ELA_RESULTS_PKEY: UniqueKey<ElaResultsRecord> = Internal.createUniqueKey(ElaResults.ELA_RESULTS, DSL.name("ela_results_pkey"), arrayOf(ElaResults.ELA_RESULTS.ID), true)
val GEOLOCATION_IMAGE_ID_KEY: UniqueKey<GeolocationRecord> = Internal.createUniqueKey(Geolocation.GEOLOCATION, DSL.name("geolocation_image_id_key"), arrayOf(Geolocation.GEOLOCATION.IMAGE_ID), true)
val GEOLOCATION_PKEY: UniqueKey<GeolocationRecord> = Internal.createUniqueKey(Geolocation.GEOLOCATION, DSL.name("geolocation_pkey"), arrayOf(Geolocation.GEOLOCATION.ID), true)
val HISTORICAL_WEATHER_IMAGE_ID_KEY: UniqueKey<HistoricalWeatherRecord> = Internal.createUniqueKey(HistoricalWeather.HISTORICAL_WEATHER, DSL.name("historical_weather_image_id_key"), arrayOf(HistoricalWeather.HISTORICAL_WEATHER.IMAGE_ID), true)
val HISTORICAL_WEATHER_PKEY: UniqueKey<HistoricalWeatherRecord> = Internal.createUniqueKey(HistoricalWeather.HISTORICAL_WEATHER, DSL.name("historical_weather_pkey"), arrayOf(HistoricalWeather.HISTORICAL_WEATHER.ID), true)
val IMAGES_PKEY: UniqueKey<ImagesRecord> = Internal.createUniqueKey(Images.IMAGES, DSL.name("images_pkey"), arrayOf(Images.IMAGES.IMAGE_ID), true)
val METADATA_PKEY: UniqueKey<MetadataRecord> = Internal.createUniqueKey(Metadata.METADATA, DSL.name("metadata_pkey"), arrayOf(Metadata.METADATA.METADATA_ID), true)
val NOISE_ANALYSIS_RESULTS_PKEY: UniqueKey<NoiseAnalysisResultsRecord> = Internal.createUniqueKey(NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS, DSL.name("noise_analysis_results_pkey"), arrayOf(NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS.ID), true)
val USERS_EMAIL_KEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), arrayOf(Users.USERS.EMAIL), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.USER_ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val DEEP_LEARNING_WEATHER_ANALIZER__DEEP_LEARNING_WEATHER_ANALIZER_IMAGE_ID_FKEY: ForeignKey<DeepLearningWeatherAnalizerRecord, ImagesRecord> = Internal.createForeignKey(DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER, DSL.name("deep_learning_weather_analizer_image_id_fkey"), arrayOf(DeepLearningWeatherAnalizer.DEEP_LEARNING_WEATHER_ANALIZER.IMAGE_ID), IMAGES_PKEY, arrayOf(Images.IMAGES.IMAGE_ID), true)
val ELA_RESULTS__FK_IMAGE: ForeignKey<ElaResultsRecord, ImagesRecord> = Internal.createForeignKey(ElaResults.ELA_RESULTS, DSL.name("fk_image"), arrayOf(ElaResults.ELA_RESULTS.IMAGE_ID), IMAGES_PKEY, arrayOf(Images.IMAGES.IMAGE_ID), true)
val GEOLOCATION__GEOLOCATION_IMAGE_ID_FKEY: ForeignKey<GeolocationRecord, ImagesRecord> = Internal.createForeignKey(Geolocation.GEOLOCATION, DSL.name("geolocation_image_id_fkey"), arrayOf(Geolocation.GEOLOCATION.IMAGE_ID), IMAGES_PKEY, arrayOf(Images.IMAGES.IMAGE_ID), true)
val HISTORICAL_WEATHER__HISTORICAL_WEATHER_IMAGE_ID_FKEY: ForeignKey<HistoricalWeatherRecord, ImagesRecord> = Internal.createForeignKey(HistoricalWeather.HISTORICAL_WEATHER, DSL.name("historical_weather_image_id_fkey"), arrayOf(HistoricalWeather.HISTORICAL_WEATHER.IMAGE_ID), IMAGES_PKEY, arrayOf(Images.IMAGES.IMAGE_ID), true)
val IMAGES__FK_USER: ForeignKey<ImagesRecord, UsersRecord> = Internal.createForeignKey(Images.IMAGES, DSL.name("fk_user"), arrayOf(Images.IMAGES.USER_ID), USERS_PKEY, arrayOf(Users.USERS.USER_ID), true)
val METADATA__METADATA_IMAGE_ID_FKEY: ForeignKey<MetadataRecord, ImagesRecord> = Internal.createForeignKey(Metadata.METADATA, DSL.name("metadata_image_id_fkey"), arrayOf(Metadata.METADATA.IMAGE_ID), IMAGES_PKEY, arrayOf(Images.IMAGES.IMAGE_ID), true)
val NOISE_ANALYSIS_RESULTS__FK_IMAGE: ForeignKey<NoiseAnalysisResultsRecord, ImagesRecord> = Internal.createForeignKey(NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS, DSL.name("fk_image"), arrayOf(NoiseAnalysisResults.NOISE_ANALYSIS_RESULTS.IMAGE_ID), IMAGES_PKEY, arrayOf(Images.IMAGES.IMAGE_ID), true)
