name: Deploy Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build -x test
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build \
            --build-arg SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ispy_be-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ispy_be-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "${{ secrets.EC2_HOST }}"
          username: "ec2-user"
          key: "${{ secrets.EC2_SSH_KEY }}"
          script: |
            echo "🚀 Deploying backend to EC2..."

            cd ~/ispy_be || exit 1

            echo "⬇️ Pulling latest backend image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ispy_be-backend:latest

            echo "🛑 Stopping old backend container..."
            docker-compose down || true
            
            echo "🚀 Running docker-compose up"
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            docker-compose up -d --build

            echo "🔄 Restarting Nginx..."
            sudo systemctl restart nginx

            echo "✅ Backend deployment complete!"
